export const QUERY_GLOBAL_NAME = "QUERY_GLOBAL_NAME";

export const UPDATE_GLOBAL_NAME = "UPDATE_GLOBAL_NAME";

export const FILTER_ALL_DATA = "FILTER_ALL_DATA";

export const FILTER_SUCCESS_STATUS =
  "FILTER_SUCCESS_STATUS";

export const FILTER_FAIL_STATUS = "FILTER_FAIL_STATUS";

export const UPDATE_FILTER_STATUS = "UPDATE_FILTER_STATUS";

export const UPDATE_IMMUTABLE_DATA =
  "UPDATE_IMMUTABLE_DATA";

export const UPDATE_REDUX_ACTIONS_DATA =
  "UPDATE_REDUX_ACTIONS_DATA";
